export const PRODUCT_ALL = 'PRODUCT_ALL';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const CHANGE_QUANTITY_CART = 'CHANGE_QUANTITY_CART';

export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';